# $Id$
#
# Makefile for rpcping
#
# 

RPCLIB = @RPCLIB@

PROGCDEFS =
PROGLIBS  = $(RPCLIB) $(OS_LIBS)

TARG =	rpcping
OBJS = 	rpcping.o

$(TARG):	$(OBJS) Makefile
	$(CC) $(CFLAGS) $(OBJS) $(PROGLIBS) -o $(TARG)

install:  installdir  $(TARG)
	$(INSTALL) -c -m 751 $(TARG) $(DESTDIR)$(BINDIR)/

clean:
	rm -f $(DIRT) $(TARG)
