PROG = snipstv
SRCS = \
	create_subwins.c \
	do_filter.c \
	help_page.c \
	init.c \
	main.c \
	parse_user_input.c \
	update_eventwin.c \
	update_msgtitle.c \
	update_msgwin.c \
	update_promptwin.c \
	update_title.c

include ../buildsys.mk
include ../misc.defs.mk

LIBS += $(CURSES_LIBS)
