# $Id$
#
# Makefile for multiping
#
# 

PROGCDEFS =
PROGLIBS  = $(OS_LIBS)

TARG =	multiping
OBJS = 	multiping.o

$(TARG):	$(OBJS) Makefile
	$(CC) $(CFLAGS) $(OBJS) $(PROGLIBS) -o $(TARG)

install:  installdir  $(TARG)
	$(INSTALL) -c -m 4711 $(TARG) $(BINDIR)/
	@if [ `whoami` = "root" ]; then \
		chown root $(BINDIR)/$(TARG) ;\
		ls -lg $(BINDIR)/$(TARG) ;\
	 else \
		echo "";echo "___Installed $(TARG) needs to be root suid___" ;\
		echo "Do as root manually" ;\
	 fi

clean:
	rm -f $(DIRT)
