# $Id$
#
# Makefile for 'ntpmon'
#

# Might need to link with 'libresolv' on some systems

PROGCDEFS =
PROGLIBS  =	# -lresolv

TARG =	ntpmon
OBJS =	main.o ntpmon.o
INITFILES = ntpmon

$(TARG): $(OBJS) Makefile
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) $(PROGLIBS) -o $@


install: installdir $(TARG)
	$(INSTALL) -c -m 751 $(TARG) $(DESTDIR)$(BINDIR)/

clean:
	rm -f $(DIRT)

rcs:
	@echo "Doing 'rcs' in `pwd`"
	@-for i in $(OBJS); do \
		$(CO) -q `basename $$i .o`.c ;\
	  done
