INCLUDES = \
	daemon.h \
	eventlog.h \
	event_utils.h \
	ndaemon.h \
	netmisc.h \
	nsmon.h \
	ntpmon.h \
	osdefs.h \
	pingmon.h \
	portmon.h \
	radiusmon.h \
	snips_funcs.h \
	snips.h \
	snipslogd.h \
	snips_main.h \
	snipstv.h \
	tpmon.h \
	trapmon.h \
	version.h

include ../buildsys.mk
