PROG = etherload
SRCS = \
	bpf.c \
	etherload.c \
	dlpi.c \
	main.c \
	nit.c \
	pfilt.c \
	snoop.c \
	linux.c \
	util.c \
	snips_specific.c \
	get_devlist.c

include ../buildsys.mk
include ../misc.defs.mk
